# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint12:
    has_velocity_limits: true
    max_velocity: 5.58505360638
    has_acceleration_limits: false
    max_acceleration: 0
  joint23:
    has_velocity_limits: true
    max_velocity: 5.58505360638
    has_acceleration_limits: false
    max_acceleration: 0
  joint34:
    has_velocity_limits: true
    max_velocity: 5.58505360638
    has_acceleration_limits: false
    max_acceleration: 0
  joint45:
    has_velocity_limits: true
    max_velocity: 5.58505360638
    has_acceleration_limits: false
    max_acceleration: 0